### ISSUE TITLE
No logro correrlo

### ISSUE THREAD

**Issue by alfonsoara** [unRob/Codigos-Postales-Mexicanos#2]
Hola, he tenido muchos problemas al intentar correrlo con la lista actualizada de Correos,

Por ultimo me marca esto;

parse_cp.rb:24:in `block in <main>': undefined method `+' for nil:NilClass (NoMethodError)

Me puedes apoyar?

**Comment by esparta** [comment]
Puedes cambiar la línea 14?

https://github.com/unRob/Codigos-Postales-Mexicanos/blob/b68986a68a96033501fd658cb152f541609b6952/parse_cp.rb#L14

para que diga esto...

```ruby
CSV.foreach("CPdescarga-utf8.txt", headers: true, encoding: "UTF-8", col_sep:'|', quote_char:'|') do |row|
```

Con eso debería funcionar.

**Comment by alfonsoara** [comment]
@esparta 

Muchas gracias!

**Comment by unRob** [comment]
Posiblemente el formato cambió, pero sin más detalles me es imposible ayudarte Alfonso. Yo comenzaría a modificar el programa para imprimir lo que está haciendo, quizá de este modo encuentres la raíz del problema. Las preguntas que me haría son: ¿Qué hace la línea 24 de `parse_cp.rb`? ¿qué parte de esa línea es `nil` inesperadamente? ¿Qué tipo de dato espero en vez de ese `nil`?

Buena suerte!

**Comment by unRob** [comment]
Ah caray! A wild @esparta appears! Gracias mano!

**Comment by esparta** [comment]
De nada, @unRob !

Lo que pasa es que estaba revisando mi dashboard, me avisó del issue, lo chequé y vi ese detalle del nombre del archivo y se me hizo curioso que su script se quejara del `nil` y no del UFT-8 como en mi caso:

```
invalid byte sequence in UTF-8 (ArgumentError)
```

Luego, como no tengo (y espero la virgencita de Guadalupe me de licencia a nunca tener) instalado MongoDB, sugerí ese cambio.
